### ISSUE TITLE
fix: String.slice() warning

### ISSUE THREAD

**Issue by miguelvillaresb** [tanguilp/wax#40] opened 2024-06-06 14:23 UTC
Module: `Wax.AttestationStatementFormat.TPM`
Issue: Calling `String.slice(2..-1)` raises a warning because is deprecated for new Elixir versions.
Fix: Replace current code by `String.slice(2..-1//1)`

I only can create an issue, not a PR but I have the fix running locally.

**Comment by tanguilp** [comment] 2024-06-06 21:25
What version of Elixir are you using? `1.16.3` doesn't raise the error.

**Comment by tanguilp** [comment] 2024-06-06 21:25
And `1.17` is not released yet

**Comment by miguelvillaresb** [comment] 2024-06-07 09:50
Erlang OTP-26.2.1
Elixir v1.16.2

This is the exception:

<img width="1457" alt="image" src="https://github.com/tanguilp/wax/assets/91469337/17acfb19-7871-42e2-bca5-cc4a9f0165e7">

**Comment by tanguilp** [comment] 2024-06-07 16:44
Sorry but can't reproduce. And I don't have any `String.slice` in `lib/wax/attestation_statement_format/tpm.ex` on line 339. Which branch are you on?

**Comment by miguelvillaresb** [comment] 2024-06-07 16:58
339 is the line where `get_tcpaTpmManufacturer_field` function is called. This function includes the slice call.

**Comment by tanguilp** [comment] 2024-06-07 19:44
Right, 5 years of Elixir and still cannot read a stacktrace correctly -_-

Still cannot reproduce though :/

**Comment by miguelvillaresb** [comment] 2024-06-09 18:49
Just adding that I am working with Rocky Linux.

**Comment by tanguilp** [comment] 2024-06-09 19:58
Thanks for the details. Closing for now as I can’t reproduce

**Closed as completed by tanguilp** 2024-06-09 19:58 UTC

**Comment by miguelvillaresb** [comment] 2024-06-09 20:12
Even If you can not reproduce just to note that ranges with negative steps in [String.slice/2] are deprecated from Elixir 1.16.
